// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43iYNJxjbszIUb4R5ejBJ8wQhS2NhDws',
    appId: '1:671789400170:web:73d180804c5d253d80ca13',
    messagingSenderId: '671789400170',
    projectId: 'fir-auth-demo-ffcf4',
    authDomain: 'fir-auth-demo-ffcf4.firebaseapp.com',
    storageBucket: 'fir-auth-demo-ffcf4.appspot.com',
    measurementId: 'G-J00XY6MZL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBueW9tLyM8VIi0rlxYUc31oFxNtt5EcJ8',
    appId: '1:671789400170:android:7d3df7d422a4449f80ca13',
    messagingSenderId: '671789400170',
    projectId: 'fir-auth-demo-ffcf4',
    storageBucket: 'fir-auth-demo-ffcf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIEyDpor62oxfVfTZaYiG6KKp_JxnP8I',
    appId: '1:671789400170:ios:608944c8cab8332880ca13',
    messagingSenderId: '671789400170',
    projectId: 'fir-auth-demo-ffcf4',
    storageBucket: 'fir-auth-demo-ffcf4.appspot.com',
    iosClientId: '671789400170-rdqus6qa1th55ad6uubfgjbfi58rap82.apps.googleusercontent.com',
    iosBundleId: 'com.malik19995.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIEyDpor62oxfVfTZaYiG6KKp_JxnP8I',
    appId: '1:671789400170:ios:608944c8cab8332880ca13',
    messagingSenderId: '671789400170',
    projectId: 'fir-auth-demo-ffcf4',
    storageBucket: 'fir-auth-demo-ffcf4.appspot.com',
    iosClientId: '671789400170-rdqus6qa1th55ad6uubfgjbfi58rap82.apps.googleusercontent.com',
    iosBundleId: 'com.malik19995.firebaseAuthDemo',
  );
}
